### ISSUE TITLE
Iterator Does Not Guarantee Standard Iteration

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/iterator-interface#3]
The [`IterationAwareInterface`] specifies return type of `getIteration()` as `mixed`. The [`IteratorInterface`] does not narrow this type. Is this a mistake, or there is a reason why the type is not [`IterationInterface`]?

[`IteratorInterface`]:                                            https://github.com/Dhii/iterator-interface/blob/release/0.1/src/IteratorInterface.php
[`IterationInterface`]:                                          https://github.com/Dhii/iterator-interface/blob/release/0.1/src/IterationInterface.php
[`IterationAwareInterface`]:                                https://github.com/Dhii/iterator-interface/blob/release/0.1/src/IterationAwareInterface.php

**Comment by XedinUnknown** [comment]
@mecha

**Comment by mecha** [comment]
Good question. Looks like a mistake that I didn't catch in my review for #1.

**Comment by XedinUnknown** [comment]
Does this mean it's OK to go fix this by narrowing?

**Comment by mecha** [comment]
I'm thinking yes.

[`IterationInterface`] is consumed as a state of the iterator, and its consumed via `getIteration()` from [`IterationAwareInterface`]. IIRC, this was one of the reasons this package was created.

Given that this method is exclusive to Dhii iterators, and the only one at that, it only makes sense to me to return an iteration object. Otherwise, the iterator might as well just extend vanilla `Iterator`.

[`IterationInterface`]: https://github.com/Dhii/iterator-interface/blob/release/0.1/src/IterationInterface.php
[`IterationAwareInterface`]: https://github.com/Dhii/iterator-interface/blob/release/0.1/src/IterationAwareInterface.php

**Comment by XedinUnknown** [comment]
Done.
